# Generated by Django 6.0.3 on 2026-05-25 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_cate_produ_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cate', models.CharField(max_length=30)),
                ('des_cate', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias_productos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_clien_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_clien', models.CharField(max_length=25)),
                ('apellido_clien', models.CharField(max_length=30)),
                ('fecha_naci_cliente', models.DateField()),
                ('tel_cliente', models.BigIntegerField()),
                ('correo_clien', models.CharField(max_length=40)),
                ('direc_clien', models.CharField(max_length=100)),
                ('estado_clien', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emple_pk', models.AutoField(db_column='id_empleado_pk', primary_key=True, serialize=False)),
                ('foto_empleado', models.CharField(default='default.png', max_length=255)),
                ('nom_emple', models.CharField(db_column='nom_empleado', max_length=50)),
                ('apellido_emple', models.CharField(db_column='apellido_empleado', max_length=50)),
                ('fecha_naci_emple', models.DateField(db_column='fecha_naci_empleado')),
                ('tipo_doc', models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte'), ('Tarjeta de Identidad', 'Tarjeta de Identidad')], max_length=50)),
                ('num_doc', models.CharField(max_length=12, unique=True)),
                ('tel_emple', models.CharField(db_column='tel_empleado', max_length=10)),
                ('correo_emple', models.CharField(db_column='correo_empleado', max_length=100, unique=True)),
                ('direc_emple', models.CharField(db_column='direc_empleado', max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('Término Indefinido', 'Término Indefinido'), ('Término Fijo', 'Término Fijo'), ('Obra o Labor', 'Obra o Labor'), ('Contrato de Aprendizaje', 'Contrato de Aprendizaje')], max_length=50)),
                ('salario_empleado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_emple', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_column='estado_empleado', default='activo', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_local_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_local', models.CharField(max_length=50)),
                ('cod_postal_local', models.IntegerField()),
            ],
            options={
                'db_table': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu_pk', models.AutoField(primary_key=True, serialize=False)),
                ('img_menu', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('nom_menu', models.CharField(max_length=60)),
                ('precio_menu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('des_menu', models.TextField()),
                ('disponible_menu', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='MesaEvento',
            fields=[
                ('id_mesa_pk', models.AutoField(primary_key=True, serialize=False)),
                ('num_mesa', models.IntegerField()),
                ('capa_mesa', models.IntegerField()),
                ('estado_mesa', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponible', max_length=10)),
            ],
            options={
                'db_table': 'mesas_eventos',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_met_pago_pk', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_met_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('bancolombia', 'Bancolombia')], max_length=20)),
                ('des_met_pago', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'metodos_pagos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_provee_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_provee', models.CharField(max_length=25)),
                ('apellido_provee', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_naci_provee', models.DateField(blank=True, null=True)),
                ('tel_provee', models.BigIntegerField()),
                ('correo_provee', models.CharField(max_length=40)),
                ('direc_provee', models.CharField(max_length=100)),
                ('estado_provee', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_role_pk', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_evento', models.CharField(max_length=30)),
                ('des_tipo_evento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_eventos',
            },
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('id_tipo_menu_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_menu', models.CharField(max_length=20)),
                ('des_tipo_menu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_menus',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_uni_medi_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_uni_medi', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=8)),
                ('tipo_uni_medi', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'unidades_medidas',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factu_pk', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factu', models.DateField()),
                ('hora_factu', models.TimeField()),
                ('total_factu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_clien_factu_fk', models.ForeignKey(db_column='id_clien_factu_fk', on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_barrio', models.CharField(max_length=50)),
                ('id_local_barrio_fk', models.ForeignKey(db_column='id_local_barrio_fk', on_delete=django.db.models.deletion.PROTECT, to='core.localidad')),
            ],
            options={
                'db_table': 'barrios',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago_pk', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('hora_pago', models.TimeField()),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_titular', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_img', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('monto_con_el_que_paga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_factu_pago_fk', models.ForeignKey(db_column='id_factu_pago_fk', on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
                ('id_met_pago_fk', models.ForeignKey(db_column='id_met_pago_fk', on_delete=django.db.models.deletion.PROTECT, to='core.metodopago')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido_pk', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12)),
                ('tipo_pedido', models.CharField(choices=[('domicilio', 'Domicilio'), ('evento', 'Evento')], max_length=10)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas_pedido', models.CharField(blank=True, max_length=200, null=True)),
                ('id_clien_pedido_fk', models.ForeignKey(db_column='id_clien_pedido_fk', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.cliente')),
                ('id_emple_pedido_fk', models.ForeignKey(blank=True, db_column='id_emple_pedido_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='core.empleado')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='id_pedido_factu_fk',
            field=models.ForeignKey(db_column='id_pedido_factu_fk', on_delete=django.db.models.deletion.PROTECT, to='core.pedido'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_evento', models.CharField(max_length=50)),
                ('fecha_evento', models.DateField()),
                ('hora_inicio_evento', models.TimeField()),
                ('hora_fin_evento', models.TimeField()),
                ('ubi_evento', models.CharField(max_length=100)),
                ('cant_invi_evento', models.IntegerField()),
                ('estado_evento', models.CharField(choices=[('pendiente', 'Pendiente'), ('en revisión', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('programado', 'Programado'), ('en progreso', 'En progreso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12)),
                ('id_mesa_evento_fk', models.ForeignKey(db_column='id_mesa_evento_fk', on_delete=django.db.models.deletion.PROTECT, to='core.mesaevento')),
                ('id_pedido_evento_fk', models.ForeignKey(db_column='id_pedido_evento_fk', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_set', to='core.pedido')),
                ('id_tipo_evento_fk', models.ForeignKey(db_column='id_tipo_evento_fk', on_delete=django.db.models.deletion.PROTECT, to='core.tipoevento')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domi_pk', models.AutoField(primary_key=True, serialize=False)),
                ('direc_domi', models.CharField(max_length=100)),
                ('fecha_domi', models.DateField()),
                ('hora_entrega_domi', models.TimeField()),
                ('estado_domi', models.CharField(choices=[('pendiente', 'Pendiente'), ('en camino', 'En camino'), ('entregado', 'Entregado')], default='pendiente', max_length=10)),
                ('id_barrio_domi_fk', models.ForeignKey(db_column='id_barrio_domi_fk', on_delete=django.db.models.deletion.PROTECT, to='core.barrio')),
                ('id_pedido_domi_fk', models.ForeignKey(db_column='id_pedido_domi_fk', on_delete=django.db.models.deletion.CASCADE, related_name='domicilios_set', to='core.pedido')),
            ],
            options={
                'db_table': 'domicilios',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoMenu',
            fields=[
                ('id_detalle_pk', models.AutoField(primary_key=True, serialize=False)),
                ('cant_detalle', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_menu_fk', models.ForeignKey(db_column='id_menu_fk', on_delete=django.db.models.deletion.PROTECT, to='core.menu')),
                ('id_pedido_fk', models.ForeignKey(db_column='id_pedido_fk', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_set', to='core.pedido')),
            ],
            options={
                'db_table': 'detalles_pedidos_menus',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_produ_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produ', models.CharField(max_length=50)),
                ('stock_actual_produ', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_minimo_produ', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fecha_venci_produ', models.DateField()),
                ('precio_uni_produ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('des_produ', models.CharField(max_length=100)),
                ('estado_produ', models.CharField(choices=[('disponible', 'Disponible'), ('no disponible', 'No Disponible'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=15)),
                ('id_cate_produ_fk', models.ForeignKey(db_column='id_cate_produ_fk', on_delete=django.db.models.deletion.PROTECT, to='core.categoriaproducto')),
                ('id_provee_produ_fk', models.ForeignKey(db_column='id_provee_produ_fk', on_delete=django.db.models.deletion.PROTECT, to='core.proveedor')),
                ('id_uni_medi_produ_fk', models.ForeignKey(db_column='id_uni_medi_produ_fk', on_delete=django.db.models.deletion.PROTECT, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id_movi_pk', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movi', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('motivo_movi', models.CharField(max_length=50)),
                ('fecha_movi', models.DateTimeField(auto_now_add=True)),
                ('cant_movi', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock_posterior', models.DecimalField(decimal_places=3, max_digits=10)),
                ('id_emple_movi_fk', models.ForeignKey(db_column='id_emple_movi_fk', on_delete=django.db.models.deletion.PROTECT, to='core.empleado')),
                ('id_produ_movi_fk', models.ForeignKey(db_column='id_produ_movi_fk', on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'db_table': 'movimientos_productos',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='id_tipo_menu_fk',
            field=models.ForeignKey(db_column='id_tipo_menu_fk', on_delete=django.db.models.deletion.PROTECT, to='core.tipomenu'),
        ),
        migrations.CreateModel(
            name='ConsumoPedido',
            fields=[
                ('id_consumo_pk', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
                ('id_pedido_fk', models.ForeignKey(db_column='id_pedido_fk', on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('id_produ_fk', models.ForeignKey(db_column='id_produ_fk', on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('id_uni_medi_fk', models.ForeignKey(db_column='id_uni_medi_fk', on_delete=django.db.models.deletion.PROTECT, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'consumos_pedidos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAuth',
            fields=[
                ('id_auth_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('correo', models.CharField(blank=True, max_length=40, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_cambio_pw', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(db_column='id_role_fk', on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
            options={
                'db_table': 'usuarios_auth',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notif_pk', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('evento', 'Evento'), ('inventario', 'Inventario'), ('pago', 'Pago'), ('cancelacion', 'Cancelación'), ('usuario', 'Usuario'), ('sistema', 'Sistema'), ('mensaje', 'Mensaje')], db_column='categoria', max_length=20)),
                ('destinatario_rol', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.CharField(max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_evento_fk', models.ForeignKey(blank=True, db_column='id_evento_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evento')),
                ('id_factura_fk', models.ForeignKey(blank=True, db_column='id_factura_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.factura')),
                ('id_movi_fk', models.ForeignKey(blank=True, db_column='id_movi_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movimientoproducto')),
                ('id_pedido_fk', models.ForeignKey(blank=True, db_column='id_pedido_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pedido')),
                ('id_producto_fk', models.ForeignKey(blank=True, db_column='id_producto_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto')),
                ('id_auth_destino_fk', models.ForeignKey(blank=True, db_column='id_auth_destino_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_recibidas', to='core.usuarioauth')),
                ('id_auth_origen_fk', models.ForeignKey(blank=True, db_column='id_auth_origen_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to='core.usuarioauth')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_auth_fk',
            field=models.OneToOneField(blank=True, db_column='id_auth_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuarioauth'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_auth_fk',
            field=models.OneToOneField(blank=True, db_column='id_auth_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuarioauth'),
        ),
        migrations.CreateModel(
            name='RecetaMenu',
            fields=[
                ('id_receta_pk', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_reque', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notas', models.CharField(blank=True, max_length=100, null=True)),
                ('id_menu_fk', models.ForeignKey(db_column='id_menu_fk', on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
                ('id_produ_fk', models.ForeignKey(db_column='id_produ_fk', on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('id_uni_medi_fk', models.ForeignKey(db_column='id_uni_medi_fk', on_delete=django.db.models.deletion.PROTECT, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'recetas_menus',
                'unique_together': {('id_menu_fk', 'id_produ_fk')},
            },
        ),
    ]
