# Generated by Django 6.0.3 on 2026-03-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_cate_produ_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cate', models.CharField(max_length=30)),
                ('des_cate', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias_productos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emple_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_emple', models.CharField(max_length=25)),
                ('apellido_emple', models.CharField(max_length=30)),
                ('fecha_naci_emple', models.DateField()),
                ('tel_emple', models.BigIntegerField()),
                ('correo_emple', models.CharField(max_length=40)),
                ('direc_emple', models.CharField(max_length=100)),
                ('estado_emple', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_provee_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_provee', models.CharField(max_length=25)),
                ('apellido_provee', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_naci_provee', models.DateField(blank=True, null=True)),
                ('tel_provee', models.BigIntegerField()),
                ('correo_provee', models.CharField(max_length=40)),
                ('direc_provee', models.CharField(max_length=100)),
                ('estado_provee', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_role_pk', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('id_tipo_menu_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_menu', models.CharField(max_length=20)),
                ('des_tipo_menu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_menus',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_uni_medi_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_uni_medi', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=8)),
                ('tipo_uni_medi', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'unidades_medidas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_produ_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produ', models.CharField(max_length=50)),
                ('stock_actual_produ', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_minimo_produ', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fecha_venci_produ', models.DateField()),
                ('precio_uni_produ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('des_produ', models.CharField(max_length=100)),
                ('estado_produ', models.CharField(choices=[('disponible', 'Disponible'), ('no disponible', 'No Disponible'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=15)),
                ('id_cate_produ_fk', models.ForeignKey(db_column='id_cate_produ_fk', on_delete=django.db.models.deletion.PROTECT, to='core.categoriaproducto')),
                ('id_provee_produ_fk', models.ForeignKey(db_column='id_provee_produ_fk', on_delete=django.db.models.deletion.PROTECT, to='core.proveedor')),
                ('id_uni_medi_produ_fk', models.ForeignKey(db_column='id_uni_medi_produ_fk', on_delete=django.db.models.deletion.PROTECT, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id_movi_pk', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movi', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('motivo_movi', models.CharField(max_length=50)),
                ('fecha_movi', models.DateTimeField(auto_now_add=True)),
                ('cant_movi', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock_posterior', models.DecimalField(decimal_places=3, max_digits=10)),
                ('id_emple_movi_fk', models.ForeignKey(db_column='id_emple_movi_fk', on_delete=django.db.models.deletion.PROTECT, to='core.empleado')),
                ('id_produ_movi_fk', models.ForeignKey(db_column='id_produ_movi_fk', on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'db_table': 'movimientos_productos',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu_pk', models.AutoField(primary_key=True, serialize=False)),
                ('img_menu', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('nom_menu', models.CharField(max_length=60)),
                ('precio_menu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('des_menu', models.TextField()),
                ('disponible_menu', models.BooleanField(default=True)),
                ('id_tipo_menu_fk', models.ForeignKey(db_column='id_tipo_menu_fk', on_delete=django.db.models.deletion.PROTECT, to='core.tipomenu')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAuth',
            fields=[
                ('id_auth_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(db_column='id_role_fk', on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
            options={
                'db_table': 'usuarios_auth',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_auth_fk',
            field=models.OneToOneField(blank=True, db_column='id_auth_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuarioauth'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_clien_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_clien', models.CharField(max_length=25)),
                ('apellido_clien', models.CharField(max_length=30)),
                ('fecha_naci_cliente', models.DateField()),
                ('tel_cliente', models.BigIntegerField()),
                ('correo_clien', models.CharField(max_length=40)),
                ('direc_clien', models.CharField(max_length=100)),
                ('estado_clien', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('id_auth_fk', models.OneToOneField(blank=True, db_column='id_auth_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuarioauth')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='RecetaMenu',
            fields=[
                ('id_receta_pk', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_reque', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notas', models.CharField(blank=True, max_length=100, null=True)),
                ('id_menu_fk', models.ForeignKey(db_column='id_menu_fk', on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
                ('id_produ_fk', models.ForeignKey(db_column='id_produ_fk', on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('id_uni_medi_fk', models.ForeignKey(db_column='id_uni_medi_fk', on_delete=django.db.models.deletion.PROTECT, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'recetas_menus',
                'unique_together': {('id_menu_fk', 'id_produ_fk')},
            },
        ),
    ]
