# Generated by Django 6.0.3 on 2026-03-30 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_local_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_local', models.CharField(max_length=50)),
                ('cod_postal_local', models.IntegerField()),
            ],
            options={
                'db_table': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='MesaEvento',
            fields=[
                ('id_mesa_pk', models.AutoField(primary_key=True, serialize=False)),
                ('num_mesa', models.IntegerField()),
                ('capa_mesa', models.IntegerField()),
                ('estado_mesa', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponible', max_length=10)),
            ],
            options={
                'db_table': 'mesas_eventos',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_evento', models.CharField(max_length=30)),
                ('des_tipo_evento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_eventos',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_barrio', models.CharField(max_length=50)),
                ('id_local_barrio_fk', models.ForeignKey(db_column='id_local_barrio_fk', on_delete=django.db.models.deletion.PROTECT, to='core.localidad')),
            ],
            options={
                'db_table': 'barrios',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido_pk', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12)),
                ('tipo_pedido', models.CharField(choices=[('domicilio', 'Domicilio'), ('evento', 'Evento')], max_length=10)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas_pedido', models.CharField(blank=True, max_length=200, null=True)),
                ('id_clien_pedido_fk', models.ForeignKey(db_column='id_clien_pedido_fk', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.cliente')),
                ('id_emple_pedido_fk', models.ForeignKey(blank=True, db_column='id_emple_pedido_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='core.empleado')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domi_pk', models.AutoField(primary_key=True, serialize=False)),
                ('direc_domi', models.CharField(max_length=100)),
                ('fecha_domi', models.DateField()),
                ('hora_entrega_domi', models.TimeField()),
                ('estado_domi', models.CharField(choices=[('pendiente', 'Pendiente'), ('en camino', 'En camino'), ('entregado', 'Entregado')], default='pendiente', max_length=10)),
                ('id_barrio_domi_fk', models.ForeignKey(db_column='id_barrio_domi_fk', on_delete=django.db.models.deletion.PROTECT, to='core.barrio')),
                ('id_pedido_domi_fk', models.ForeignKey(db_column='id_pedido_domi_fk', on_delete=django.db.models.deletion.CASCADE, related_name='domicilios_set', to='core.pedido')),
            ],
            options={
                'db_table': 'domicilios',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoMenu',
            fields=[
                ('id_detalle_pk', models.AutoField(primary_key=True, serialize=False)),
                ('cant_detalle', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_menu_fk', models.ForeignKey(db_column='id_menu_fk', on_delete=django.db.models.deletion.PROTECT, to='core.menu')),
                ('id_pedido_fk', models.ForeignKey(db_column='id_pedido_fk', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_set', to='core.pedido')),
            ],
            options={
                'db_table': 'detalles_pedidos_menus',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nom_evento', models.CharField(max_length=50)),
                ('fecha_evento', models.DateField()),
                ('hora_inicio_evento', models.TimeField()),
                ('hora_fin_evento', models.TimeField()),
                ('ubi_evento', models.CharField(max_length=100)),
                ('cant_invi_evento', models.IntegerField()),
                ('estado_evento', models.CharField(choices=[('pendiente', 'Pendiente'), ('en revisión', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('programado', 'Programado'), ('en progreso', 'En progreso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12)),
                ('id_mesa_evento_fk', models.ForeignKey(db_column='id_mesa_evento_fk', on_delete=django.db.models.deletion.PROTECT, to='core.mesaevento')),
                ('id_pedido_evento_fk', models.ForeignKey(db_column='id_pedido_evento_fk', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_set', to='core.pedido')),
                ('id_tipo_evento_fk', models.ForeignKey(db_column='id_tipo_evento_fk', on_delete=django.db.models.deletion.PROTECT, to='core.tipoevento')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
    ]
