# Generated by Django 6.0.3 on 2026-05-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_cliente',
            field=models.CharField(default='default.png', max_length=255),
        ),
    ]
