# Generated by Django 6.0.3 on 2026-03-30 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_localidad_mesaevento_tipoevento_barrio_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_met_pago_pk', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_met_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('bancolombia', 'Bancolombia')], max_length=20)),
                ('des_met_pago', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'metodos_pagos',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factu_pk', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factu', models.DateField()),
                ('hora_factu', models.TimeField()),
                ('total_factu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_clien_factu_fk', models.ForeignKey(db_column='id_clien_factu_fk', on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('id_pedido_factu_fk', models.ForeignKey(db_column='id_pedido_factu_fk', on_delete=django.db.models.deletion.PROTECT, to='core.pedido')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago_pk', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('hora_pago', models.TimeField()),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('id_factu_pago_fk', models.ForeignKey(db_column='id_factu_pago_fk', on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
                ('id_met_pago_fk', models.ForeignKey(db_column='id_met_pago_fk', on_delete=django.db.models.deletion.PROTECT, to='core.metodopago')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
