# Generated by Django 6.0.3 on 2026-05-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_foto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel_cliente',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tel_provee',
            field=models.CharField(max_length=10),
        ),
    ]
