# Generated by Django 6.0.3 on 2026-04-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_metodopago_factura_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='celular_origen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante_img',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_con_el_que_paga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='nombre_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
