# Generated by Django 6.0.3 on 2026-06-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_tel_cliente_alter_proveedor_tel_provee'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoproducto',
            name='nota_movi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='origen_movi',
            field=models.CharField(default='manual', max_length=20),
        ),
    ]
