# Generated by Django 6.0.3 on 2026-06-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movimientoproducto_nota_movi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='apellido_provee',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_naci_provee',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categorias_provee',
            field=models.ManyToManyField(blank=True, db_table='proveedor_categorias', to='core.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condicion_pago_provee',
            field=models.CharField(blank=True, choices=[('contado', 'Contado'), ('15_dias', '15 días'), ('30_dias', '30 días'), ('60_dias', '60 días')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nit_cedula_provee',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_contacto_provee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones_provee',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_provee',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('persona_natural', 'Persona Natural')], default='empresa', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_provee',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nom_provee',
            field=models.CharField(max_length=100),
        ),
    ]
