# Generated by Django 6.0.3 on 2026-04-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pago_celular_origen_pago_comprobante_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notif_pk', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('reserva', 'Reserva'), ('inventario', 'Inventario'), ('mensaje', 'Mensaje del Cliente')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
    ]
