# Generated by Django 6.0.3 on 2026-06-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_proveedor_apellido_provee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_solicitud_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_solicitud_cancelacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitud_cancelacion_pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id_historial_pk', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=12)),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=12)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=300, null=True)),
                ('id_auth_fk', models.ForeignKey(blank=True, db_column='id_auth_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuarioauth')),
                ('id_pedido_fk', models.ForeignKey(db_column='id_pedido_fk', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='core.pedido')),
            ],
            options={
                'db_table': 'historial_estados_pedidos',
            },
        ),
    ]
