# Generated by Django 6.0.3 on 2026-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedido_fecha_solicitud_cancelacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='estado_domi',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual_produ__gte', 0)), name='stock_actual_no_negativo'),
        ),
    ]
