# Generated by Django 6.0.3 on 2026-06-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_domicilio_estado_domi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='id_mesa_evento_fk',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='id_pedido_evento_fk',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='id_tipo_evento_fk',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='id_evento_fk',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pedido', 'Pedido'), ('inventario', 'Inventario'), ('pago', 'Pago'), ('cancelacion', 'Cancelación'), ('usuario', 'Usuario'), ('sistema', 'Sistema'), ('mensaje', 'Mensaje')], db_column='categoria', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(default='domicilio', editable=False, max_length=20),
        ),
        migrations.DeleteModel(
            name='MesaEvento',
        ),
        migrations.DeleteModel(
            name='TipoEvento',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
