# Generated by Django 6.0.3 on 2026-06-08 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_evento_id_mesa_evento_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='id_pedido_pago_fk',
            field=models.ForeignKey(blank=True, db_column='id_pedido_pago_fk', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pedido'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_factu_pago_fk',
            field=models.ForeignKey(blank=True, db_column='id_factu_pago_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.factura'),
        ),
    ]
