# Generated by Django 6.0.3 on 2026-06-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pago_id_pedido_pago_fk_alter_pago_id_factu_pago_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id_config_pk', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor_booleano', models.BooleanField(default=False)),
                ('valor_texto', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
