# Generated by Django 6.0.3 on 2026-06-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuracionsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nom_produ',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo_produ__gt', 0)), name='stock_minimo_positivo'),
        ),
    ]
