# Generated by Django 6.0.3 on 2026-06-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_poblar_localidades_barrios'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id_carrito_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('id_cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('id_menu_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
            ],
            options={
                'db_table': 'tbl_carrito_items',
                'unique_together': {('id_cliente_fk', 'id_menu_fk')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('id_cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('id_menu_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
            ],
            options={
                'db_table': 'tbl_favoritos',
                'unique_together': {('id_cliente_fk', 'id_menu_fk')},
            },
        ),
    ]
