# Generated by Django 6.0.3 on 2026-07-01 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_carritoitem_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaEmail',
            fields=[
                ('id_campana_pk', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('total_destinatarios', models.IntegerField(default=0)),
                ('enviado_por_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuarioauth')),
            ],
            options={
                'db_table': 'tbl_campanas_email',
            },
        ),
    ]
